# Feature Scaling Solution Notebook

### Importing Libraries

In [11]:
import pandas as pd
import numpy as np

### Importing Dataset

In [12]:
df = pd.read_csv("Dataset_03.csv")
df.head(15)

    Australia  Canada  Dubai  USA  Salary  YearsExperience  Purchased
0           0       0      1    0   39343              1.1          0
1           0       1      0    0   46205              1.3          1
2           0       1      0    0   37731              1.5          0
3           0       1      0    0   43525              2.0          0
4           0       0      0    1   39891              2.2          0
5           0       0      1    0   56642              2.9          0
6           0       1      0    0   60150              3.0          1
7           1       0      0    0   54445              3.2          0
8           0       0      1    0   64445              3.2          1
9           0       0      1    0   57189              3.7          0
10          0       0      1    0   63218              3.9          1
11          0       0      0    1   55794              4.0          0
12          0       0      1    0   56957              4.0          1
13          0       1      0    0   57081              4.1          0
14          1       0      0    0   61111              4.5          0

In [13]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

### Splitting Dataset

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size = 0.2, random_state = 1)

### Perform Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train.iloc[:,4:] = sc.fit_transform(X_train.iloc[:,4:])

/tmp/ipykernel_651/2959258548.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.4613054  -1.06760255  1.20174835  0.92184131  1.35259996 -1.1927326
 -1.2671082   1.06921517 -0.4951515   0.23527882 -0.60082683 -0.6915926
  1.31207215 -0.97532172 -0.29271904 -1.21160197 -0.22698617  1.63013111
  1.64800192 -0.59710805 -0.34726114 -0.60509654 -0.64514229 -0.61594298]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X_train.iloc[:,4:] = sc.fit_transform(X_train.iloc[:,4:])

In [17]:
X_test.iloc[:,4:] = sc.transform(X_test.iloc[:,4:])

/tmp/ipykernel_651/3773846790.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.29467599  0.81754331 -0.38951061  0.66834449 -0.46206125  0.5925227 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X_test.iloc[:,4:] = sc.transform(X_test.iloc[:,4:])

### Check it

In [16]:
X_train

    Australia  Canada  Dubai  USA    Salary  YearsExperience
26          0       0      1    0  1.461305         1.391080
3           0       1      0    0 -1.067603        -1.058963
24          0       0      1    0  1.201748         1.129742
22          1       0      0    0  0.921841         0.868404
23          1       0      0    0  1.352600         0.966406
4           0       0      0    1 -1.192733        -0.993629
2           0       1      0    0 -1.267108        -1.222299
25          1       0      0    0  1.069215         1.227744
6           0       1      0    0 -0.495152        -0.732291
18          1       0      0    0  0.235279         0.215059
13          0       1      0    0 -0.600827        -0.372951
7           1       0      0    0 -0.691593        -0.666956
27          0       0      0    1  1.312072         1.423747
1           0       1      0    0 -0.975322        -1.287634
16          0       0      0    1 -0.292719        -0.046279
0           0       0      1    0 -1.211602        -1.352968
15          0       0      0    1 -0.226986        -0.111613
29          0       1      0    0  1.630131         1.717753
28          0       0      0    1  1.648002         1.652418
9           0       0      1    0 -0.597108        -0.503620
8           0       0      1    0 -0.347261        -0.666956
12          0       0      1    0 -0.605097        -0.405618
11          0       0      0    1 -0.645142        -0.405618
5           0       0      1    0 -0.615943        -0.764958

In [18]:
X_test

    Australia  Canada  Dubai  USA    Salary  YearsExperience
17          0       1      0    0  0.294676         0.019056
21          1       0      0    0  0.817543         0.607066
10          0       0      1    0 -0.389511        -0.438286
19          0       1      0    0  0.668344         0.247727
14          1       0      0    0 -0.462061        -0.242282
20          0       1      0    0  0.592523         0.509065